# data.py

_MOCK_RESTAURANTS_DB = {
    "seller001": {"name": "ElectroGadgets", "category": "Electronics", "avg_rating": 4.5, "city": "Metroville"},
    "seller002": {"name": "HomeEssentials", "category": "Home & Kitchen", "avg_rating": 4.2, "city": "Metroville"},
    "seller003": {"name": "FashionForward", "category": "Apparel", "avg_rating": 4.8, "city": "Metroville"},
    "seller004": {"name": "BookNook", "category": "Books", "avg_rating": 4.6, "city": "Suburbia"},
    "seller005": {"name": "FitLife Gear", "category": "Sports & Fitness", "avg_rating": 4.3, "city": "Metroville"},
    "seller006": {"name": "ToyTopia", "category": "Toys & Games", "avg_rating": 4.0, "city": "Suburbia"},
    "seller007": {"name": "BeautyBliss", "category": "Beauty & Personal Care", "avg_rating": 4.7, "city": "Metroville"},
    "seller008": {"name": "Gourmet Pantry", "category": "Groceries", "avg_rating": 4.9, "city": "Metroville"},
}

_MOCK_DELIVERY_AGENTS_DB = {
    "logi01": {"name": "SpeedyShip Logistics", "service_level": "Express", "rating": 4.7, "operational_area": "Metroville North"},
    "logi02": {"name": "Metro Couriers", "service_level": "Standard", "rating": 4.9, "operational_area": "Metroville South"},
    "logi03": {"name": "EcoDeliveries", "service_level": "Standard", "rating": 4.5, "operational_area": "Suburbia West"},
    "logi04": {"name": "SecureHaul Inc.", "service_level": "Express", "rating": 4.8, "operational_area": "Metroville Central"},
}

_MOCK_ORDERS_DB = {
    "ORDZW001": {
        "status": "Processing",
        "items": ["Wireless Keyboard", "USB-C Hub"],
        "customer_id": "cust001",
        "restaurant_id": "seller001",
        "delivery_address": "123 Main St, Metroville, 12345",
        "delivery_agent_id": None,
        "order_total": 85.99,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "2-3 business days",
        "special_instructions": "Please use discreet packaging."
    },
    "ORDZW002": {
        "status": "Out for Delivery",
        "items": ["Queen Size Bed Sheet Set", "Pillow Covers (Set of 2)"],
        "customer_id": "cust002",
        "restaurant_id": "seller002",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "logi01",
        "order_total": 45.50,
        "payment_method": "PayPal",
        "estimated_delivery_time": "Arriving today",
        "special_instructions": "Leave package with the concierge."
    },
    "ORDZW003": {
        "status": "Delivered",
        "items": ["Men's Graphic T-Shirt", "Skinny Jeans"],
        "customer_id": "cust001",
        "restaurant_id": "seller003",
        "delivery_address": "123 Main St, Metroville, 12345",
        "delivery_agent_id": "logi02",
        "order_total": 72.75,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered yesterday",
        "special_instructions": None
    },
    "ORDZW004": {
        "status": "Cancelled",
        "items": ["Hardcover Sci-Fi Novel", "Bookmark Set"],
        "customer_id": "cust003",
        "restaurant_id": "seller004",
        "delivery_address": "789 Pine Rd, Suburbia, 54321",
        "delivery_agent_id": None,
        "order_total": 32.00,
        "payment_method": "COD",
        "estimated_delivery_time": None,
        "special_instructions": "Customer cancelled."
    },
    "ORDZW005": {
        "status": "Shipped",
        "items": ["Yoga Mat", "Resistance Bands"],
        "customer_id": "cust004",
        "restaurant_id": "seller005",
        "delivery_address": "101 Maple Dr, Metroville, 12347",
        "delivery_agent_id": None,
        "order_total": 35.25,
        "payment_method": "GreatBuy Wallet",
        "estimated_delivery_time": "3-5 business days",
        "special_instructions": "Gift wrapping requested."
    },
    "ORDZW006": {
        "status": "Delivered",
        "items": ["LEGO City Set", "Remote Control Car"],
        "customer_id": "cust005",
        "restaurant_id": "seller006",
        "delivery_address": "222 Birch Ln, Suburbia, 54322",
        "delivery_agent_id": "logi03",
        "order_total": 99.80,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered 2 days ago",
        "special_instructions": "Leave at front porch."
    },
    "ORDZW007": {
        "status": "Out for Delivery",
        "items": ["Vitamin C Serum"],
        "customer_id": "cust002",
        "restaurant_id": "seller007",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "logi04",
        "order_total": 26.50,
        "payment_method": "PayPal",
        "estimated_delivery_time": "Arriving by 8 PM",
        "special_instructions": "Handle with care, fragile item."
    },
    "ORDZW008": {
        "status": "Delivered",
        "items": ["Organic Coffee Beans", "Artisanal Honey"],
        "customer_id": "cust006",
        "restaurant_id": "seller008",
        "delivery_address": "333 Willow Cr, Metroville, 12348",
        "delivery_agent_id": "logi01",
        "order_total": 32.00,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "Delivered last week",
        "special_instructions": None
    },
    "ORDZW009": {
        "status": "Processing",
        "items": ["Gaming Mouse", "Mousepad"],
        "customer_id": "cust007",
        "restaurant_id": "seller001",
        "delivery_address": "414 Cedar Pl, Suburbia, 54323",
        "delivery_agent_id": None,
        "order_total": 70.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "2-4 business days",
        "special_instructions": "Ensure box is sealed properly."
    },
    "ORDZW010": {
        "status": "Issue Reported",
        "items": ["Air Fryer", "Kitchen Towels"],
        "customer_id": "cust002",
        "restaurant_id": "seller002",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "logi02",
        "order_total": 115.00,
        "payment_method": "PayPal",
        "estimated_delivery_time": "Resolved",
        "special_instructions": "Customer reported item was damaged, replacement sent."
    },
    "ORDZW011": {
        "status": "Awaiting Shipment",
        "items": ["Summer Dress", "Sun Hat"],
        "customer_id": "cust008",
        "restaurant_id": "seller003",
        "delivery_address": "505 Spruce St, Metroville, 12349",
        "delivery_agent_id": None,
        "order_total": 89.00,
        "payment_method": "GreatBuy Wallet",
        "estimated_delivery_time": "4-6 business days",
        "special_instructions": "Include gift receipt."
    },
    "ORDZW012": {
        "status": "Payment Failed",
        "items": ["History Textbook", "Notebook (Set of 3)"],
        "customer_id": "cust009",
        "restaurant_id": "seller004",
        "delivery_address": "606 Redwood Ave, Suburbia, 54324",
        "delivery_agent_id": None,
        "order_total": 58.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": None,
        "special_instructions": "Payment declined, please update payment method."
    },
    "ORDZW013": {
        "status": "Delivered",
        "items": ["Dumbbell Set (5kg)", "Jump Rope"],
        "customer_id": "cust010",
        "restaurant_id": "seller005",
        "delivery_address": "707 Elm Rd, Metroville, 12350",
        "delivery_agent_id": "logi03",
        "order_total": 48.75,
        "payment_method": "COD",
        "estimated_delivery_time": "Delivered 3 days ago",
        "special_instructions": None
    },
    "ORDZW014": {
        "status": "Shipped",
        "items": ["Board Game"],
        "customer_id": "cust011",
        "restaurant_id": "seller006",
        "delivery_address": "808 Aspen Ct, Suburbia, 54325",
        "delivery_agent_id": None,
        "order_total": 29.99,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "Arriving in 2 days",
        "special_instructions": "Do not bend package."
    },
    "ORDZW015": {
        "status": "Out for Delivery",
        "items": ["Anti-aging Face Cream", "Lipstick"],
        "customer_id": "cust012",
        "restaurant_id": "seller007",
        "delivery_address": "909 Fir Way, Metroville, 12351",
        "delivery_agent_id": "logi04",
        "order_total": 65.20,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Arriving by 5 PM",
        "special_instructions": "Signature required upon delivery."
    },
    "ORDZW016": {
        "status": "Delivered",
        "items": ["Imported Pasta (Pack of 4)"],
        "customer_id": "cust013",
        "restaurant_id": "seller008",
        "delivery_address": "111 Juniper Pl, Suburbia, 54326",
        "delivery_agent_id": "logi01",
        "order_total": 26.00,
        "payment_method": "GreatBuy Wallet",
        "estimated_delivery_time": "Delivered yesterday",
        "special_instructions": "Happy Birthday message on packing slip."
    },
    "ORDZW017": {
        "status": "Cancelled by Seller",
        "items": ["4K Television (55-inch)"],
        "customer_id": "cust014",
        "restaurant_id": "seller001",
        "delivery_address": "222 Sycamore Dr, Metroville, 12352",
        "delivery_agent_id": None,
        "order_total": 499.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": None,
        "special_instructions": "Sorry, item is out of stock."
    },
    "ORDZW018": {
        "status": "Processing",
        "items": ["Electric Kettle"],
        "customer_id": "cust015",
        "restaurant_id": "seller002",
        "delivery_address": "333 Magnolia Ave, Suburbia, 54327",
        "delivery_agent_id": None,
        "order_total": 31.75,
        "payment_method": "PayPal",
        "estimated_delivery_time": "3-5 business days",
        "special_instructions": "Please ensure it is the red color model."
    },
    "ORDZW019": {
        "status": "Awaiting Shipment",
        "items": ["Leather Handbag", "Silk Scarf"],
        "customer_id": "cust016",
        "restaurant_id": "seller003",
        "delivery_address": "444 Poplar St, Metroville, 12353",
        "delivery_agent_id": None,
        "order_total": 127.80,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "Ships in 24 hours",
        "special_instructions": None
    },
    "ORDZW020": {
        "status": "Delivered",
        "items": ["The Lord of the Rings Trilogy (Box Set)"],
        "customer_id": "cust017",
        "restaurant_id": "seller004",
        "delivery_address": "555 Chestnut Rd, Suburbia, 54328",
        "delivery_agent_id": "logi02",
        "order_total": 55.15,
        "payment_method": "COD",
        "estimated_delivery_time": "Delivered this morning",
        "special_instructions": "Thank you for your purchase!"
    },
    "ORDZW021": {
        "status": "Out for Delivery",
        "items": ["Protein Powder (Chocolate)", "Shaker Bottle"],
        "customer_id": "cust018",
        "restaurant_id": "seller005",
        "delivery_address": "666 Hemlock Cr, Metroville, 12354",
        "delivery_agent_id": "logi03",
        "order_total": 59.90,
        "payment_method": "GreatBuy Wallet",
        "estimated_delivery_time": "Arriving today by 9 PM",
        "special_instructions": "Ensure shaker bottle is BPA-free."
    },
    "ORDZW022": {
        "status": "Shipped",
        "items": ["Jigsaw Puzzle (1000 pieces)", "Playing Cards"],
        "customer_id": "cust019",
        "restaurant_id": "seller006",
        "delivery_address": "777 Cypress Ln, Suburbia, 54329",
        "delivery_agent_id": None,
        "order_total": 33.40,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Arriving in 3 days",
        "special_instructions": "Pack in a sturdy box."
    },
    "ORDZW023": {
        "status": "Delivered",
        "items": ["Shampoo & Conditioner Set", "Face Wash"],
        "customer_id": "cust005",
        "restaurant_id": "seller007",
        "delivery_address": "222 Birch Ln, Suburbia, 54322",
        "delivery_agent_id": "logi04",
        "order_total": 46.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered 4 days ago",
        "special_instructions": "This is a recurring subscription order."
    }
}

_MOCK_WIKI_DB = {
    "premium membership": "GreatBuy Premium offers free shipping on all eligible orders, exclusive deals, and access to exclusive content & early deals. It costs $14.99/month or $139/year.",
    "GreatBuy premium benefits": "GreatBuy Premium offers free shipping on all eligible orders, exclusive deals, and access to exclusive content & early deals. It costs $14.99/month or $139/year.",
    "GreatBuy membership": "GreatBuy offers a Premium membership with benefits like free shipping and exclusive deals. It costs $14.99/month or $139/year.",
    "membership benefits": "GreatBuy Premium members enjoy free shipping on eligible orders, exclusive deals, and access to exclusive content & early deals.",
    "shipping fees": "Shipping fees vary based on the item size, weight, and your location. GreatBuy Premium members enjoy free shipping on eligible orders. You'll see the exact fee at checkout.",
    "cancel order policy": "You can cancel an order free of charge if it has not yet been shipped (usually within a few hours of placing the order). Once an item has shipped, it cannot be cancelled but can be returned. Check your order status in the app for cancellation options.",
    "return policy": "If you receive a wrong, damaged, or defective item, please initiate a return through the 'My Orders' page within 30 days of delivery. We'll provide a shipping label and process a refund or replacement once the item is received. For issues noted in your order like for ORDZW010, actions like replacements may have already been processed.",
    "minimum order value": "Some sellers may have a minimum order value to qualify for shipping. This will be indicated on the seller's page or at checkout.",
    "GreatBuy for business": "GreatBuy offers corporate accounts for businesses looking for office supplies, client gifting, or employee perks. Contact corpsales@GreatBuy.com for more details.",
    "product quality and authenticity": "GreatBuy partners with reputable sellers. We have strict policies against counterfeit goods. If you have concerns about an item's authenticity, please report it to support immediately.",
    "estimated delivery dates": "Estimated delivery dates are calculated based on seller processing time, shipping service, and your address. While we strive for accuracy, unforeseen carrier delays can occur.",
    "track my order": "You can track your order in real-time via the GreatBuy app or website. You'll receive a tracking number as soon as your order is shipped.",
    "payment methods accepted": "GreatBuy accepts major credit/debit cards (Visa, MasterCard, Amex), PayPal, GreatBuy Wallet, and Cash on Delivery (COD) for select orders and locations.",
    "update billing information": "To update your payment methods, go to 'Account Settings' in the GreatBuy app or website, then select 'Payment Methods'. You can add, remove, or set a default payment option.",
    "password reset": "If you've forgotten your password, click the 'Forgot Password?' link on the login screen. Enter your registered email address, and we'll send you instructions to reset it.",
    "data privacy policy": "Your privacy is important. Our policy, available at GreatBuy.com/privacy, explains how we collect, use, and protect your personal information. GreatBuy is compliant with relevant data protection regulations.",
    "terms of service": "Our terms of service outline your rights and responsibilities when using GreatBuy. You can find them at GreatBuy.com/terms.",
    "contact support": "For any issues, contact GreatBuy support via in-app chat, email at support@GreatBuy.com, or call 1-800-GreatBuy (24/7). Please have your order ID ready.",
    "about GreatBuy": "GreatBuy is your one-stop online marketplace, connecting you with thousands of sellers for millions of products. Our mission is to deliver anything you need, right to your doorstep.",
    "how to become a delivery partner": "GreatBuy partners with established logistics companies. If you represent a logistics provider, please contact logistics-partners@GreatBuy.com.",
    "list my products on GreatBuy": "Sellers can expand their reach by partnering with GreatBuy. Visit GreatBuy.com/sellers for information on how to join our platform and start selling.",
    "how to become a seller on GreatBuy": "Sellers can expand their reach by partnering with GreatBuy. Visit GreatBuy.com/sellers for information on how to join our platform and start selling.",
    "how to register as a seller on GreatBuy": "Sellers can expand their reach by partnering with GreatBuy. Visit GreatBuy.com/sellers for information on how to join our platform and start selling.",
    "partner with GreatBuy": "Sellers can expand their reach by partnering with GreatBuy. Visit GreatBuy.com/sellers for information on how to join our platform and start selling.",
    "sell on GreatBuy": "Sellers can expand their reach by partnering with GreatBuy. Visit GreatBuy.com/sellers for information on how to join our platform and start selling.",
    "referral program": "Share your GreatBuy referral code with friends! When they make their first purchase, you both get a $10 credit. Find your code in the 'Promotions' section of the app.",
    "product information": "Sellers provide all product details, including specifications, dimensions, and materials. Please read the product description carefully. For more specific questions, you can use the 'Ask a question' feature on the product page.",
    "what if my package is late?": "We apologize for any delays. You can check the latest tracking status in your order details. If it's significantly late or the tracking hasn't updated, please contact GreatBuy support for assistance.",
    "rating your purchase": "After your item is delivered, you can rate the product and the seller. Your feedback helps other customers and helps us maintain a quality marketplace.",
    "GreatBuy wallet": "GreatBuy Wallet is a convenient way to pay. Add funds using your preferred payment method and enjoy faster checkouts. Refunds and promotional credits are often issued to your Wallet.",
    "pre-orders": "Yes, you can pre-order upcoming products from select sellers. Your payment method will be charged when the item ships. Look for the 'Pre-order' button on eligible items.",
    "gift options": "Planning to send a gift? Many sellers offer gift wrapping and personalized messages. Look for the 'This is a gift' option at checkout."
}